name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: KrbRelayUp.exe
        path: D:\a\KrbRelayUp\KrbRelayUp\KrbRelayUp\bin\Release\KrbRelayUp.exe
